import { IConnection } from '@genai-fi/base';

export const CONNECTIONS: IConnection[] = [
    {
        start: 'thread',
        end: 'checkmodel',
        startPoint: 'right',
        endPoint: 'left',
        endOffset: 0.0,
        startOffset: 0.2,
    },
    {
        start: 'checkmodel',
        end: 'textData',
        startPoint: 'right',
        endPoint: 'left',
        endOffset: -0.5,
        startOffset: 0.5,
    },
    {
        start: 'textData',
        end: 'tokeniser',
        startPoint: 'right',
        endPoint: 'left',
        endOffset: -0.5,
        startOffset: -0.1,
    },
    {
        start: 'tokeniser',
        end: 'tokeniseData',
        startPoint: 'bottom',
        endPoint: 'top',
        endOffset: -0.2,
        startOffset: 0.2,
    },
    {
        start: 'tokeniser',
        end: 'vocabulary',
        startPoint: 'right',
        endPoint: 'left',
        startOffset: 0.2,
    },
    {
        start: 'tokeniseData',
        end: 'trainer',
        startPoint: 'right',
        endPoint: 'left',
        startOffset: -0.4,
        endOffset: -0.2,
    },
    {
        start: 'tokeniseData',
        end: 'tokenised-data',
        startPoint: 'right',
        endPoint: 'left',
        startOffset: 0.2,
    },
    {
        start: 'trainer',
        end: 'chatOutput',
        startPoint: 'right',
        endPoint: 'left',
        startOffset: 0.5,
        endOffset: 0.6,
    },
    {
        start: 'trainer',
        end: 'training-monitor',
        startPoint: 'right',
        endPoint: 'left',
        startOffset: 0,
    },
    {
        start: 'trainer',
        end: 'training-visualize',
        startPoint: 'right',
        endPoint: 'left',
        startOffset: 0.0,
    },
    {
        start: 'chatOutput',
        end: 'tuneData',
        startPoint: 'right',
        endPoint: 'left',
        startOffset: -0.3,
        endOffset: -0.5,
    },
    {
        start: 'chatOutput',
        end: 'inference-visualize',
        startPoint: 'right',
        endPoint: 'left',
        startOffset: -0.2,
    },
    {
        start: 'tuneData',
        end: 'finetuner',
        startPoint: 'right',
        endPoint: 'left',
        startOffset: 0.2,
        endOffset: 0.0,
    },
    {
        start: 'finetuner',
        end: 'sharing',
        startPoint: 'right',
        endPoint: 'left',
        startOffset: -0.2,
        endOffset: -0.4,
    },
    {
        start: 'finetuner',
        end: 'tuning-monitor',
        startPoint: 'right',
        endPoint: 'left',
        startOffset: 0,
    },
    {
        start: 'sharing',
        end: 'conversationOutput',
        startPoint: 'right',
        endPoint: 'left',
        startOffset: 0.6,
    },
];
